import time
seconds = time.time()
print("your seconds: ", seconds)
local_time = time.ctime(seconds)
print(local_time)
print("print immedately")
#time.sleep(5)
print("this is after sleep function")
result = time.localtime(seconds)
print(result)
print("time Zone: ",result.tm_zone)
print("year: ",result.tm_year)
print("hour: ",result.tm_hour)
print("month: ",result.tm_mon)

python_time = time.gmtime()

print(python_time)
print(('year',python_time.tm_year))

t = (2018, 12, 28, 8, 44, 4, 4, 362, 0)
l_time = time.mktime(t)
print(l_time)
t2 =time.localtime(l_time)
print(t2)
t3 = time.asctime(t)
print(t3)
t4 = time.localtime()
time_format= time.strftime("%m/%d/%y, %H:%M:%S",t4)
time_format1= time.strftime("%m/%d/%Y")
print(time_format)
print(time_format1)